# About the Author {-}

\markboth{ABOUT THE AUTHOR}{ABOUT THE AUTHOR}

Melinda Higgins got her Bachelor of Science (BS) degree with a double major in math and chemistry in 1989 from Saint Andrews Presbyterian College in Laurinburg, NC. She then received dual graduate degrees in Chemometrics (PhD, 1994) and Statistics (MS, 1995) from the University of Suth Carolina. She has over 30 years experience in research, teaching, consulting, directing and managing projects. Her expertise includes programming and scripting languages (R, S, Pascal, Perl, Prolog) and statistical, mathematical, imaging, and geo-spatial processing software packages (R, SAS, SPSS, MATLAB, SYSTAT, ENVI, ESRI ArcView, ERDAS IMAGINE). Her professional career began with 17 years (1995-2011) at the Georgia Tech Research Institute, Atlanta, GA where she was the program director for the National Guard Bureau Technology Consortium. As director, she coordinated large team projects with rigorous timelines, milestone tracking and version control in the areas of remote sensing, geospatial information systems, sensor fusion and target recognition. In 2007, she began her current work at Emory University, Atlanta, GA where she now has over a decade of expertise mentoring students and faculty in nursing and public health science research and scholarship. Her health research experience includes pattern recognition of disease phenotype characterizations through data mining and longitudinal modeling of clinical trial interventions in heart failure, diabetes, cognitive impairment, and HIV/AIDS chronic disease populations. She is also the creator and instructor for Emory NRSG 736 Quantitative Analysis of Clinical Research Data (https://melindahiggins2000.github.io/N736/); Emory NRSG 741 Big Data Analytics for Healthcare (https://melindahiggins2000.github.io/N741bigdata/); "R for SAS Users" on Datacamp (https://www.datacamp.com/courses/r-for-sas-users); and "Reproducible Templates for Analysis and Dissemination" on Coursera (https://www.coursera.org/learn/reproducible-templates-analysis). She is a native of Atlanta, GA, co-founder of R-Ladies Atlanta (https://www.meetup.com/rladies-atlanta/) and current vice-chair of district 5 for the American Statistical Association (https://ww2.amstat.org/committees/commdetails.cfm?txtComm=COCGB or https://www.amstat.org/ASA/Membership/Chapters.aspx).


