# Exercise with GIT & Github {#gitexercise}

## Using Git and Github

Now that you have Git installed on your computer and you’ve created your Github account, let's test your setup.

1. Open your browser and log back into your Github account
2. Click on your Profile, and then Click on Repositories – now we’re going to create a new repository
3. Click NEW to create a new repository.
    a. type in a name for your repository such as "MyFirstRepo"
    b. put in a short description like "My First Github Repository"
    c. this will be a PUBLIC repository, but as you can see if you have paid for a PRIVATE Github account you do have the option to create Private repositories
    d. Go ahead and click the box to select "Initialize this repository with a README"
    e. keep everything else the same (use the defaults)
    f. click "Create Repository"

It takes a moment for the repository to be created, but you’ll notice that your repository now has 1 file in it. README.md, which is your readme for the repository.

Now we’re going to connect everything back to your local drive using Git.

We need to create a place on your local drive where you want to save your work for this course. We’re going to end up creating multiple repositories for this course, so I create a central folder on your computer like `C:\RepTemplates` where you'll keep everything organized.

You can see this folder created on my computer. It is this folder where I will store and link all of my Github repositories for this course.

Let’s go ahead and run GIT. As I mentioned, we will use the Git Bash command window for running and executing GIT commands.

Once the GIT Bash window opens, you’ll see some information and details in the window about what directory/folder it's currently in. On my system, GIT Bash defaults to my “users” directory. 

However, we want to change out of this directory. Keep typing 

`cd ..`

until you get to the main “C” drive. Then we’re going to change to the RepTemplates folder we just created. Type 

`cd RepTemplates`

You should see the directory folder change at the GIT Bash command line, but you can also type the command

`pwd`

To get the “path with directory” to verify that you ended in your `C:\RepTemplates` folder as intended.

We can also view the contents of this folder, by typing either

`ls`

To “list” the files in this directory or you can also type

`dir`

To get a “directory” listing of the contents. You’ll notice at the moment there is nothing in this folder. That's fine. That's correct. In a minute we’re going to link back up to our newly create Github repository “MyFirstRepo”.

[END computer demo]

As we go through this course, I will refer many times to the book by Jenny Bryan entitled: Happy Git and Github for the useR

You can access this book for FREE online at [http://happygitwithr.com/](http://happygitwithr.com/) There's a lot of good information on setting up R and RStudio and for getting setup using Git and Github.

[BEGIN computer demo]

Now to get started using GIT, you need to “introduce yourself.” At this point, you should already be logged into your Github account. But we need to make sure that GIT understands how to talk to your Github account. So, we’re going to type in 3 GIT commands in your GIT Bash window. Open your GIT Bash window.

This first command tells GIT your name – be sure to type in the same name you used when you set up your Github account. Your name goes between the 2 single quote marks.

`git config --global user.name 'Jennifer Bryan'`

Next we also have to tell GIT the email account you used when you set up your Github account. Again put your email in between the 2 single quote marks.

`git config --global user.email 'jenny@stat.ubc.ca'`

Finally, to check to make sure everything went in correctly, type in the following GIT command to list your global settings and you should see the user.name and user.email you just typed in. 

`git config --global –list`

If you see these, CONGRATULATIONS you have successfully introduced yourself to GIT!!

KEEP your GIT Bash window open.

[END computer demo]

"pushmi-pullyu" SLIDE with PUSH / PULL GRAPHIC – insert here

We'll be using the terms PUSH and PULL to talk about moving files back and forth from our local computer to the Github cloud repository and from the cloud back to our local computer.

The “pushmi-pullyu” was a fictional animal in the Doctor Dolittle series of children's books by Hugh Lofting with two heads on opposite ends of its body, so you never knew if the animal was coming or going.

Hopefully, we won’t have that confusion in this course, but we will be PUSH'ing and PULL'ing content in and out of your project repository between your local computer and your Github account using Git version control. 

A PULL moves content from the cloud to your local computer.

A PUSH moves content from your local computer to the cloud.

[BEGIN computer demo]

Now let's CLONE your Github repository to copy the repository contents from your Github cloud repository down to your local computer.

Open your browser, and go to your “MyFirstRepo” repository. At the top right, there's a green button to “Clone or Download” your repository. Just below that green button, there's a little icon to the right to “copy to the clipboard” the long URL address you will need when we use GIT to clone your repository.

[END computer demo]

First PULL to Clone your repository SLIDE – insert graphic illustrating a PULL from the cloud

When you CLONE your repository, this is your first PULL. You will be PULLing the content down from your Github account to your local computer.

[BEGIN computer demo]

To execute a clone using GIT, open your GIT Bash window. Check to make sure you are in your `C:\RepTemplates` directory. 

Go back to the “MyFirstRepo” repository and click “copy to clipboard” to get the Github repo URL. Make sure you have the option for “Clone with HTTPS” shown to get the correct URL.

Back in GIT Bash, Type git clone followed by the URL. Since the URL is now COPYied into your “clipboard”, you can PASTE it into the GIT Bash window

`git clone https://github.com/melindahiggins2001/MyFirstRepo.git`

This will take a minute to run, but it should say that it is cloning your repository and you should not get any errors.

Now type in a ls or dir command to view the contents of your directory. You should now see a new folder created called “MyFirstRepo” in your `C:\RepTemplates` directory. 

Then type in 

`cd MyFirstRepo`

to change into this new directory and type ls or dir to view the contents. VIOLA!! You should now see the `README.md` file in this directory.

You can also see this file by viewing the directory contents in your file explorer. You may also be able to see a hidden folder called `/.git` which was created when you did the clone. If you can’t see this folder, that’s OK- it’s usually hidden by default. I changed the settings on my computer so I can view these hidden folders.

[END computer demo]

TADA!! You have now successfully cloned your Github repository and have it linked from your local computer to Github using version control and tracking with GIT!!

We’re going to do this again in the next part using the RStudio interface.

## Using the RStudio Interface

Let’s take a moment and look at some of the other content in the Happy Git and Github for the user book by Jenny Bryan. [http://happygitwithr.com/](http://happygitwithr.com/).

There are many chapters in this book you may want to read and take a look at. For example, chapter 5 has information on setting up a Github account and chapter 6 has information on installing or upgrading both R and RStudio which you’ve already done. And chapter 7 covers installing Git which you’ve also already done.

Then in Chapter 8 there is information on introducing yourself to GIT which you’ve just completed.

If you would like to move beyond using just the Git Bash window and command line interface for using Git for version control, I recommend reading Chapter 9 on installing a more full-featured Git client. Jenny Bryan recommends either SourceTree or GitKracken. 

Chapter 10 covers getting connected to Github which you just completed.

We’re going to spend some time in this next part of the lesson, learning about setting up credentials on your computer using either HTTPS or SSH to securely connect to your Github account. These details are covered in chapters 11 and 12.

There is additional information in chapters 13, 14 and 15 on using RStudio with Git to connect to Github and manage your projects. I will be showing you how to use RStudio to connect to Github using Git shortly.

The later chapters 16, 17 and 18 provide examples of linking up projects with Github depending on whether the project is new or existing and whether you setup the project on Github first or last. For the projects we will be doing in this course, we will be creating new projects by setting up Github first.

The next section of the book provides some workflow examples. I point out Chapter 22 which covers Git commands some of which you’ve already learned. I also mention Chapter 26 entitled Burn it all down which is helpful to read when you have problems and Git stops communicating between Github and RStudio.

Now we’re going to connect to your Github account using Git but from the RStudio interface instead of from the Git Bash window. Go ahead and start RStudio.

When you open RStudio you should see a screen similar to this but it won’t look exactly like this and that is OK. Your layout should be similar. There are a few options we need to review and setup to make sure that RStudio known that you want to use Git.

In the tools menu, click on Global options. Click on the button for GIT/SVN. In this window we want to make sure that the box is checked for “enable version control interface for RStudio projects”. Next we need to find where the GIT executable file is located on your computer. On my computer it is located on my program files folder for Git/bin. For example, if I click browse it shows where this is on my computer’s hard drive. You’ll notice that the file is named “git.exe” and is located in the “/bin” folder. You may also see an icon like the one shown here next to the filename. There is also a similar file under the “/cmd” folder, but this is NOT the one we want. We also DO NOT want the file for “git-bash.exe” NOR the one names “git-cmd.exe”

Also make sure you have the box checked for “Use Git Bash as shell for Git projects”. This why I showed you earlier how to use the Git Bash shell window with your projects.

Since we’re not using SVN you can ignore the line for SVN executable

[END COMPUTER DEMO]

[BACK TO SLIDES]

Now that we’ve got some of the options setup in RStudio for using Git, we next need to setup your Github account credentials on your computer so that each time you run a GIT command to connect and sync to your Github account you won’t have to keep typing in your login name and password. You can setup your credentials by using either HTTPS (hyper text transfer protocol secure) or SSH (Secure Shell). These are two different approaches for setting up your credentials. I’m going to show you how to setup SSH from RStudio. 

[BEGIN COMPUTER DEMO]

Back in RStudio in the Global options window for Git/SVN options, were going to setup your SSH RSA Key. This is for setting up a public key/private key cryptosystem. Click on the button to “Create RSA Key” and use the defaults. This is where you create the key. You can add a pass phrase or password, but this is optional. Note where on your hard drive it tells you where the security key will be created. Then click “create” to create your key. If you’d like to view your public key, click on the link to the right. Once you’re done, click OK

Let’s double check that GIT also now sees your SSH Key. Open your Git Bash window and type in this command

`ls –al ~/.ssh`

When you do this, you should see two files `id_rsa` (which is your private key) and `id_rsa.pub` (which is your public key). This is explained in more detail in the Happy Git book in chapter 12.2. You can also click the `[?]` Using Version Control with RStudio to get to the help webpages at RStudio.

Make sure you are in the local directory for your new repository `C:/RepTemplates/MyFirstRepo`. You should see this listed in your Git Bash window prompt or you can also type pwd to get the “path with directory”

You can double check your settings in the git bash window by typing

`git config –global --list`

You should be pretty much setup and ready to go at this point. If you are still getting errors, you might have a credentialing conflict. For example, if you have multiple Github accounts with different emails, you might have to remove one credential and add the other one instead. Search Stack Overflow [https://stackoverflow.com/](https://stackoverflow.com/) or the Github help documentation [https://help.github.com/](https://help.github.com/) for help.

Let’s go back to RStudio and create a New Project. 

